### ISSUE TITLE
кузнечик

### ISSUE THREAD

**Issue by kisttan** [vlsergey/infosec#4328]
Думаю стоит упомянуть что из стандарта убрали описание режимов шифрования - вывели в отдельный стандарт ГОСТ Р 34.13-2015. По описанию все вроде бы ок, со стандартом сходится. Для схемы  формирования сеансовых ключей лучше нарисовать картинку, описание довольно путанным получилось, в самом стандарте стройнее на мой взгляд.
Что касается атак, появляются новые, местами очень смелые )) исследования, вот например http://www.ivdon.ru/uploads/article/pdf/IVD_176_Maro.pdf_81fed81a84.pdf
рассматривается в виде RFC5742  вот эхо обсуждения http://search.gmane.org/?query=34.12-2015&group=gmane.ietf.irtf.cfrg в итоге приняли как информационный без номера вот здесь https://datatracker.ietf.org/doc/draft-dolmatov-kuznyechik/

**Comment by vlsergey** [comment]
Про отдельный стандарт упомянул; картинку чуть расширил; добавил явно про размер блока и ключа в начало раздела. Про атаки хотелось бы писать про те, про которые кто-нибудь упоминал. Писать про Инженерный вестник Дона... Лучше подождать.

**Comment by vlsergey** [comment]
про схему формирования ещё дописал.

**Comment by kisttan** [comment]
Про Вестник Дона согласен, да )))

Отправлено с iPhone
