### ISSUE TITLE
Too long subtitles

### ISSUE THREAD

**Issue by ghost** [vlsergey/infosec#5]
Слишком длинные подзаголовки. Как следствие заголовок не помещается в верхний колонтитул. Список заголовков:
    3.2. Российский стандарт...
    4.4. Три способа...
    5.2. Российский стандарт...
    6. Криптосистемы с открытым .... (Глава)
    7.3. Протоколы ...
    9.3. Шифрование ...
    9.6. Защита персональных ...
  10.4. Хранение паролей и аутентификация ...
  11.1. Контроль доступа ....
  11.4. Переполнение ....
  11.6. SQL-инъекции....
   А.2. Конечные ....
   А.5. Группа точек ....
   А.6. Полиномиальные и ....

**Comment by vlsergey** [comment]
Вроде в настоящий момент все длинные заголовки поправлены
