### ISSUE TITLE
! LaTeX Error: File `cjhebrew.sty' not found.

### ISSUE THREAD

**Issue by Dmitry-N-Medvedev** [vlsergey/infosec#5286]

**Comment by pavelkryukov** [comment]
На каком дистрибутиве происходит ошибка? В MiKTeX можно установить вручную через Package Manager.

**Comment by Dmitry-N-Medvedev** [comment]
Linux mint 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u3 (2017-08-15) x86_64 GNU/Linux

**Comment by pavelkryukov** [comment]
Теоретически, устанавливаться пакет должен командой

```bash
tlmgr install cjhebrew
mktexlsr # нужно для обновления базы данных
```

На Ubuntu, по всей видимости, используется устаревшая версия TeXLive 2015, поэтому нужно ещё изменить путь к репозиторию, как советуют здесь: https://tex.stackexchange.com/questions/313768/why-getting-this-error-tlmgr-unknown-directive

```bash
tlmgr option repository ftp://tug.org/historic/systems/texlive/2015/tlnet-final
tlmgr install cjhebrew
mktexlsr
```

Затем необходимо настроить шрифты. Здесь нужно сделать следующую правку в исходном коде, в ближайшее время отправлю pull request
```diff
diff --git a/Information Security.tex b/Information Security.tex
index 0455e74..3ed5afd 100644
--- a/Information Security.tex  
+++ b/Information Security.tex  
@@ -44,6 +44,7 @@
 \usepackage{wrapfig}                   % sub figures
 \usepackage{textcomp}                   % \No support
 \usepackage{cjhebrew}
+\pdfmapfile{=cjhebrew.map}

 \usepackage[left=1.84cm, right=1.5cm, paperwidth=14cm, top=1.8cm, bottom=2cm, height=19.8cm, paperheight=20cm]{geometry}
 \usepackage[parentracker=true,
```

**Comment by orsinium** [comment]
Была та же проблема, на Linux Mint 18, ядро 4.4.0-53-generic. Решил следующим способом:
```
sudo apt install xzdec
tlmgr init-usertree
tlmgr option repository ftp://tug.org/historic/systems/texlive/2015/tlnet-final
tlmgr install cjhebrew
sudo mktexlsr
```
А вот патч из комментария выше не применял, т.к. иначе компилятор LaTeX'а ругается на отсутствие маппинга `=cjhebrew.map`. На первый взгляд, собралось как надо.

**Comment by pavelkryukov** [comment]
Тогда разумным будет откатить изменения. Параллельно поинтересуюсь у израильских коллег о кошерном способе вставить иврит в текст.

**Comment by vlsergey** [comment]
За последние время с miktex проблем под Windows не возникало
