### ISSUE TITLE
Небезопасные интервалы в схеме Эль-Гамаля (el-gamal.tex)

### ISSUE THREAD

**Issue by And42** [vlsergey/infosec#6001]
В шифровании по Эль-Гамалю предлагается брать секретный ключ в диапазоне [0, p - 1]. Это не очень хорошее решение с точки зрения безопасности. Лучше исключить 0, 1 и p - 1 из множества возможных значений. Аргумент: при выборе x = 0 или x = p - 1, открытый ключ (y = g^x mod p) будет равен 1 (и только при этих двух значениях). Из-за этого злоумышленник, зная p и что y = 1, проверяет два возможных значения секретного ключа (0 и p - 1) вместо долгого и нудного поиска алгоритмами. Для единицы ситуация похожая - g^x mod p = g при x = 1. Зная, что y = g, злоумышленник принимает x = 1, минуя всю защиту.
> \item Выбирает $x \in [0, p - 1]$ с помощью генератора случайных чисел.

То же самое можно сказать про
> \item Сторона $B$ выбирает случайное число $r \in [1, p-1]$ и вычисляет:
в этом случае r =1 и r = p - 1 находятся без особых усилий

**Comment by vlsergey** [comment]
Спасибо, уточнил интервалы.
